### ISSUE TITLE
Can't use Options or Lists of non-primitive types inside messages when using Protobuf serialization (regression)

### ISSUE THREAD

**Issue by L-Lavigne** [frees-io/freestyle-rpc#285]
I found this out while upgrading the old Metrifier project - at some point after freestyle-rpc 0.3.0, we've lost the ability to handle Lists or Options of non-primitive messages types within an RPC message class. This affects only Protobuf serialization (not Avro).

For example:
```
case class Person(attribs: List[String])
```
works, but
```
case class PersonList(ps: List[Person])
```
doesn't. The exception looks like this:
```
[error] (run-main-0) io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
[error] io.grpc.StatusRuntimeException: CANCELLED: Failed to read message.
[error] 	at io.grpc.Status.asRuntimeException(Status.java:526)
[error] 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:467)
[error] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37)
[error] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[error] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[error] 	at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:684)
[error] 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:37)
[error] 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
[error] 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
[error] 	at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:391)
[error] 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:471)
[error] 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:553)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:474)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:538)
[error] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[error] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.util.NoSuchElementException: head of empty list
[error] 	at scala.collection.immutable.Nil$.head(List.scala:428)
[error] 	at scala.collection.immutable.Nil$.head(List.scala:425)
[error] 	at pbdirect.PBParserImplicits.$anonfun$requiredParser$1(PBReader.scala:152)
[error] 	at pbdirect.PBParserImplicits.$anonfun$requiredParser$1$adapted(PBReader.scala:141)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1(PBReader.scala:106)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1$adapted(PBReader.scala:105)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1(PBReader.scala:106)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1$adapted(PBReader.scala:105)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1(PBReader.scala:106)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1$adapted(PBReader.scala:105)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.PBReaderImplicits.$anonfun$prodReader$1(PBReader.scala:41)
[error] 	at pbdirect.LowerPriorityPBReaderImplicits$$anon$1.read(PBReader.scala:17)
[error] 	at pbdirect.PBParserImplicits.$anonfun$requiredParser$1(PBReader.scala:148)
[error] 	at pbdirect.PBParserImplicits.$anonfun$requiredParser$1$adapted(PBReader.scala:141)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1(PBReader.scala:106)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1$adapted(PBReader.scala:105)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1(PBReader.scala:106)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1$adapted(PBReader.scala:105)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.PBReaderImplicits.$anonfun$prodReader$1(PBReader.scala:41)
[error] 	at pbdirect.LowerPriorityPBReaderImplicits$$anon$1.read(PBReader.scala:17)
[error] 	at pbdirect.PBParserImplicits.$anonfun$repeatedParser$1(PBReader.scala:134)
[error] 	at pbdirect.PBParserImplicits.$anonfun$repeatedParser$1$adapted(PBReader.scala:127)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1(PBReader.scala:106)
[error] 	at pbdirect.LowPriorityPBParserImplicits.$anonfun$consParser$1$adapted(PBReader.scala:105)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.PBReaderImplicits.$anonfun$prodReader$1(PBReader.scala:41)
[error] 	at pbdirect.LowerPriorityPBReaderImplicits$$anon$1.read(PBReader.scala:17)
[error] 	at pbdirect.PBParserImplicits.$anonfun$requiredParser$1(PBReader.scala:148)
[error] 	at pbdirect.PBParserImplicits.$anonfun$requiredParser$1$adapted(PBReader.scala:141)
[error] 	at pbdirect.LowPriorityPBParserImplicits$$anon$2.parse(PBReader.scala:97)
[error] 	at pbdirect.package$PBParserOps$.pbTo$extension(package.scala:26)
[error] 	at freestyle.rpc.internal.encoders$pbd$$anon$1.parse(encoders.scala:71)
[error] 	at io.grpc.MethodDescriptor.parseResponse(MethodDescriptor.java:266)
[error] 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:526)
[error] 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
[error] 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by fedefernandez** [comment]
Related to https://github.com/btlines/pbdirect/issues/21
