### ISSUE TITLE
@rpc Service with Boolean Types as Request

### ISSUE THREAD

**Issue by juanpedromoreno** [frees-io/freestyle-rpc#67]
Services with a method like the following:

```scala
@rpc def listPersons(b: Boolean): FS[PersonList]
```

It'll generate a bug when invoking it from the derived client:

```bash
io.grpc.StatusRuntimeException: CANCELLED: Failed to stream message
	at io.grpc.Status.asRuntimeException(Status.java:526) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:433) ~[grpc-stub-1.6.1.jar:1.6.1]
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:422) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:61) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:504) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:425) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:536) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:102) ~[grpc-core-1.6.1.jar:1.6.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: com.google.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
	at com.google.protobuf.InvalidProtocolBufferException.truncatedMessage(InvalidProtocolBufferException.java:82) ~[protobuf-java-3.3.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readRawBytes(CodedInputStream.java:1186) ~[protobuf-java-3.3.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readByteArray(CodedInputStream.java:846) ~[protobuf-java-3.3.1.jar:na]
	at pbdirect.package$PBWriterOps.toPB(package.scala:16) ~[pbdirect_2.12-0.0.5.jar:0.0.5]
	at freestyle.rpc.internal.service.encoders$$anon$1.stream(service.scala:236) ~[frees-rpc_2.12-0.1.1.jar:0.1.1]
	at io.grpc.MethodDescriptor.streamRequest(MethodDescriptor.java:269) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.internal.ClientCallImpl.sendMessage(ClientCallImpl.java:388) ~[grpc-core-1.6.1.jar:1.6.1]
	at io.grpc.stub.ClientCalls.asyncUnaryRequestCall(ClientCalls.java:237) ~[grpc-stub-1.6.1.jar:1.6.1]
	at io.grpc.stub.ClientCalls.futureUnaryCall(ClientCalls.java:169) ~[grpc-stub-1.6.1.jar:1.6.1]
	at freestyle.rpc.internal.client.calls$.unary(calls.scala:43) ~[frees-rpc_2.12-0.1.1.jar:0.1.1]
```

However, changing to 

```scala
@rpc def listPersons(b: String): FS[PersonList]
```

It works as expected.

We shouldn't discard other basic types apart from `Boolean`.

**Comment by juanpedromoreno** [comment]
I'm providing a test case where the issue is shown up: https://github.com/frees-io/freestyle-rpc/pull/68 (tagged as `ignore`).

**Comment by juanpedromoreno** [comment]
We cannot use a primitive type as either the request or response, we have to use a message type. I'm closing it.
